<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('menus')->delete();

        \DB::table('menus')->insert(array (
            0 =>
            array (
                'id' => 26,
                'name' => '首页',
                'pid' => 0,
                'status' => 1,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::index',
                'url' => '/admin/index',
                'group' => '',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-02-28 12:50:35',
                'updated_at' => '2020-02-02 11:02:52',
            ),
            1 =>
            array (
                'id' => 27,
                'name' => '管理员列表',
                'pid' => 26,
                'status' => 1,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::adminUser.index',
                'url' => '/admin/admin_users',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-02-28 12:50:35',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            2 =>
            array (
                'id' => 28,
                'name' => '管理员列表数据',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 2,
                'route' => 'admin::adminUser.list',
                'url' => '/admin/admin_users/list',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-02-28 12:50:35',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            3 =>
            array (
                'id' => 29,
                'name' => '新增管理员',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 2,
                'route' => 'admin::adminUser.create',
                'url' => '/admin/admin_users/create',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-02-28 12:50:35',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            4 =>
            array (
                'id' => 30,
                'name' => '保存管理员',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::adminUser.save',
                'url' => '/admin/admin_users',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-02-28 12:50:35',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            5 =>
            array (
                'id' => 31,
                'name' => '编辑管理员',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 2,
                'route' => 'admin::adminUser.edit',
                'url' => '',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-02-28 12:50:35',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            6 =>
            array (
                'id' => 32,
                'name' => '更新管理员',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 2,
                'route' => 'admin::adminUser.update',
                'url' => '',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-02-28 12:50:35',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            7 =>
            array (
                'id' => 33,
                'name' => '菜单列表',
                'pid' => 26,
                'status' => 1,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::menu.index',
                'url' => '/admin/menus',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-02-28 12:50:35',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            8 =>
            array (
                'id' => 34,
                'name' => '菜单列表数据',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::menu.list',
                'url' => '/admin/menus/list',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-02-28 12:50:35',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            9 =>
            array (
                'id' => 35,
                'name' => '新增菜单',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 2,
                'route' => 'admin::menu.create',
                'url' => '/admin/menus/create',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-02-28 12:50:35',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            10 =>
            array (
                'id' => 36,
                'name' => '保存菜单',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::menu.save',
                'url' => '/admin/menus',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-02-28 12:50:35',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            11 =>
            array (
                'id' => 37,
                'name' => '编辑菜单',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 2,
                'route' => 'admin::menu.edit',
                'url' => '',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-02-28 12:50:35',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            12 =>
            array (
                'id' => 38,
                'name' => '更新菜单',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::menu.update',
                'url' => '',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-02-28 12:50:35',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            13 =>
            array (
                'id' => 40,
                'name' => '系统管理',
                'pid' => 26,
                'status' => 1,
                'is_lock_name' => 1,
                'order' => 1,
                'route' => 'admin::config.index',
                'url' => '/admin/configs',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => NULL,
                'updated_at' => '2019-03-21 17:07:49',
            ),
            14 =>
            array (
                'id' => 41,
                'name' => '自动更新菜单',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::menu.discovery',
                'url' => '/admin/menus/discovery',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-02-28 15:36:34',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            15 =>
            array (
                'id' => 43,
                'name' => '角色列表',
                'pid' => 26,
                'status' => 1,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::role.index',
                'url' => '/admin/roles',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-01 14:17:26',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            16 =>
            array (
                'id' => 44,
                'name' => '角色列表数据接口',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::role.list',
                'url' => '/admin/roles/list',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-01 14:17:26',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            17 =>
            array (
                'id' => 45,
                'name' => '新增角色',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 2,
                'route' => 'admin::role.create',
                'url' => '/admin/roles/create',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-01 14:17:26',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            18 =>
            array (
                'id' => 46,
                'name' => '保存角色',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::role.save',
                'url' => '/admin/roles',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-01 14:17:26',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            19 =>
            array (
                'id' => 47,
                'name' => '编辑角色',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::role.edit',
                'url' => '',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-01 14:17:26',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            20 =>
            array (
                'id' => 48,
                'name' => '更新角色',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::role.update',
                'url' => '',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-01 14:17:26',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            21 =>
            array (
                'id' => 49,
                'name' => '分配角色',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::adminUser.role.edit',
                'url' => '',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-01 16:54:43',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            22 =>
            array (
                'id' => 50,
                'name' => '更新用户角色',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::adminUser.role.update',
                'url' => '',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-01 16:54:43',
                'updated_at' => '2019-03-21 16:37:32',
            ),
            23 =>
            array (
                'id' => 51,
                'name' => '分配权限',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::role.permission.edit',
                'url' => '',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-02 12:04:28',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            24 =>
            array (
                'id' => 52,
                'name' => '更新权限',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::role.permission.update',
                'url' => '',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-02 12:04:28',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            25 =>
            array (
                'id' => 53,
                'name' => '配置列表数据接口',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::config.list',
                'url' => '/admin/configs/list',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-04 12:09:17',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            26 =>
            array (
                'id' => 54,
                'name' => '新增配置',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 7,
                'route' => 'admin::config.create',
                'url' => '/admin/configs/create',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-04 12:09:17',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            27 =>
            array (
                'id' => 55,
                'name' => '保存配置',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::config.save',
                'url' => '/admin/configs',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-04 12:09:17',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            28 =>
            array (
                'id' => 56,
                'name' => '编辑配置',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::config.edit',
                'url' => '',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-04 12:09:17',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            29 =>
            array (
                'id' => 57,
                'name' => '更新配置',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::config.update',
                'url' => '',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-04 12:09:17',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            30 =>
            array (
                'id' => 58,
                'name' => '日志列表',
                'pid' => 26,
                'status' => 1,
                'is_lock_name' => 0,
                'order' => 10,
                'route' => 'admin::log.index',
                'url' => '/admin/logs',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-06 09:53:46',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            31 =>
            array (
                'id' => 59,
                'name' => '日志列表数据接口',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::log.list',
                'url' => '/admin/logs/list',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-06 09:53:46',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            32 =>
            array (
                'id' => 61,
                'name' => '批量操作',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::menu.batch',
                'url' => '/admin/menus/batch',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-06 16:03:14',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            33 =>
            array (
                'id' => 62,
                'name' => '内容管理',
                'pid' => 0,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 4,
                'route' => 'admin::aggregation',
                'url' => '/admin/aggregation',
                'group' => '',
                'guard_name' => 'admin',
                'remark' => '内容管理',
                'created_at' => '2019-03-06 17:01:30',
                'updated_at' => '2020-02-14 11:23:50',
            ),
            34 =>
            array (
                'id' => 64,
                'name' => '删除菜单',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::menu.delete',
                'url' => '',
                'group' => '基础功能',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-07 09:45:17',
                'updated_at' => '2019-03-07 16:52:51',
            ),
            35 =>
            array (
                'id' => 79,
                'name' => '广告位列表',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 20,
                'route' => 'admin::category.index',
                'url' => '/admin/categories',
                'group' => '广告管理',
                'guard_name' => 'admin',
                'remark' => '0',
                'created_at' => '2019-03-08 08:57:30',
                'updated_at' => '2021-04-12 07:14:33',
            ),
            36 =>
            array (
                'id' => 80,
                'name' => '广告位列表数据接口',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::category.list',
                'url' => '/admin/categories/list',
                'group' => '广告管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 08:57:30',
                'updated_at' => '2019-03-08 09:07:41',
            ),
            37 =>
            array (
                'id' => 81,
                'name' => '新增广告位',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 21,
                'route' => 'admin::category.create',
                'url' => '/admin/categories/create',
                'group' => '广告管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 08:57:30',
                'updated_at' => '2019-03-15 10:30:28',
            ),
            38 =>
            array (
                'id' => 82,
                'name' => '保存广告位',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::category.save',
                'url' => '/admin/categories',
                'group' => '广告管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 08:57:30',
                'updated_at' => '2019-03-08 09:07:11',
            ),
            39 =>
            array (
                'id' => 83,
                'name' => '编辑广告位',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::category.edit',
                'url' => '',
                'group' => '广告管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 08:57:30',
                'updated_at' => '2019-03-08 09:07:11',
            ),
            40 =>
            array (
                'id' => 84,
                'name' => '更新广告位',
                'pid' => 26,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::category.update',
                'url' => '',
                'group' => '广告管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 08:57:30',
                'updated_at' => '2019-03-08 09:07:11',
            ),
            41 =>
            array (
                'id' => 86,
                'name' => '模型列表',
                'pid' => 62,
                'status' => 1,
                'is_lock_name' => 0,
                'order' => 0,
                'route' => 'admin::entity.index',
                'url' => '/admin/entities',
                'group' => '模型管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 11:57:54',
                'updated_at' => '2019-03-08 14:24:23',
            ),
            42 =>
            array (
                'id' => 87,
                'name' => '模型列表数据接口',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::entity.list',
                'url' => '/admin/entities/list',
                'group' => '模型管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 11:57:54',
                'updated_at' => '2019-03-08 11:58:50',
            ),
            43 =>
            array (
                'id' => 88,
                'name' => '新增模型',
                'pid' => 62,
                'status' => 1,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::entity.create',
                'url' => '/admin/entities/create',
                'group' => '模型管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 11:57:54',
                'updated_at' => '2019-03-08 11:58:31',
            ),
            44 =>
            array (
                'id' => 89,
                'name' => '保存模型',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::entity.save',
                'url' => '/admin/entities',
                'group' => '模型管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 11:57:54',
                'updated_at' => '2019-03-08 11:58:31',
            ),
            45 =>
            array (
                'id' => 90,
                'name' => '编辑模型',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::entity.edit',
                'url' => '',
                'group' => '模型管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 11:57:54',
                'updated_at' => '2019-03-08 11:58:31',
            ),
            46 =>
            array (
                'id' => 91,
                'name' => '更新模型',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::entity.update',
                'url' => '',
                'group' => '模型管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 11:57:54',
                'updated_at' => '2019-03-08 11:58:31',
            ),
            47 =>
            array (
                'id' => 92,
                'name' => '删除模型',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::entity.delete',
                'url' => '',
                'group' => '模型管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 11:57:54',
                'updated_at' => '2019-03-08 11:58:31',
            ),
            48 =>
            array (
                'id' => 93,
                'name' => '模型字段列表',
                'pid' => 62,
                'status' => 1,
                'is_lock_name' => 0,
                'order' => 10,
                'route' => 'admin::entityField.index',
                'url' => '/admin/entityFields',
                'group' => '模型字段管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 14:10:31',
                'updated_at' => '2019-03-12 13:37:19',
            ),
            49 =>
            array (
                'id' => 94,
                'name' => '模型字段列表数据接口',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::entityField.list',
                'url' => '/admin/entityFields/list',
                'group' => '模型字段管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 14:10:31',
                'updated_at' => '2019-03-08 14:11:20',
            ),
            50 =>
            array (
                'id' => 95,
                'name' => '新增模型字段',
                'pid' => 62,
                'status' => 1,
                'is_lock_name' => 0,
                'order' => 11,
                'route' => 'admin::entityField.create',
                'url' => '/admin/entityFields/create',
                'group' => '模型字段管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 14:10:31',
                'updated_at' => '2019-03-12 13:37:39',
            ),
            51 =>
            array (
                'id' => 96,
                'name' => '保存模型字段',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::entityField.save',
                'url' => '/admin/entityFields',
                'group' => '模型字段管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 14:10:31',
                'updated_at' => '2019-03-08 14:11:08',
            ),
            52 =>
            array (
                'id' => 97,
                'name' => '编辑模型字段',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::entityField.edit',
                'url' => '',
                'group' => '模型字段管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 14:10:31',
                'updated_at' => '2019-03-08 14:11:08',
            ),
            53 =>
            array (
                'id' => 98,
                'name' => '更新模型字段',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::entityField.update',
                'url' => '',
                'group' => '模型字段管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 14:10:31',
                'updated_at' => '2019-03-08 14:11:08',
            ),
            54 =>
            array (
                'id' => 99,
                'name' => '删除模型字段',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::entityField.delete',
                'url' => '',
                'group' => '模型字段管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-08 14:10:31',
                'updated_at' => '2019-03-08 14:11:08',
            ),
            55 =>
            array (
                'id' => 118,
                'name' => '删除模板',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 77,
                'route' => 'admin::template.delete',
                'url' => '',
                'group' => '模板管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-27 14:00:59',
                'updated_at' => '2019-03-27 14:08:20',
            ),
            56 =>
            array (
                'id' => 117,
                'name' => '更新模板',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 77,
                'route' => 'admin::template.update',
                'url' => '',
                'group' => '模板管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-27 14:00:59',
                'updated_at' => '2019-03-27 14:08:20',
            ),
            57 =>
            array (
                'id' => 116,
                'name' => '编辑模板',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 77,
                'route' => 'admin::template.edit',
                'url' => '',
                'group' => '模板管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-27 14:00:59',
                'updated_at' => '2019-03-27 14:08:20',
            ),
            58 =>
            array (
                'id' => 115,
                'name' => '保存模板',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 77,
                'route' => 'admin::template.save',
                'url' => '/admin/templates',
                'group' => '模板管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-27 14:00:59',
                'updated_at' => '2019-03-27 14:08:20',
            ),
            59 =>
            array (
                'id' => 114,
                'name' => '新增模板',
                'pid' => 62,
                'status' => 1,
                'is_lock_name' => 0,
                'order' => 55,
                'route' => 'admin::template.create',
                'url' => '/admin/templates/create',
                'group' => '模板管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-27 14:00:59',
                'updated_at' => '2019-03-27 14:09:25',
            ),
            60 =>
            array (
                'id' => 113,
                'name' => '模板列表数据接口',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 77,
                'route' => 'admin::template.list',
                'url' => '/admin/templates/list',
                'group' => '模板管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-27 14:00:59',
                'updated_at' => '2019-03-27 14:08:20',
            ),
            61 =>
            array (
                'id' => 112,
                'name' => '模板列表',
                'pid' => 62,
                'status' => 1,
                'is_lock_name' => 0,
                'order' => 55,
                'route' => 'admin::template.index',
                'url' => '/admin/templates',
                'group' => '模板管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-03-27 14:00:59',
                'updated_at' => '2019-03-27 14:09:25',
            ),
            62 =>
            array (
                'id' => 125,
                'name' => '删除会员',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 100,
                'route' => 'admin::user.delete',
                'url' => '',
                'group' => '会员管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-04-04 09:04:35',
                'updated_at' => '2019-04-04 09:06:41',
            ),
            63 =>
            array (
                'id' => 124,
                'name' => '更新会员',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 100,
                'route' => 'admin::user.update',
                'url' => '',
                'group' => '会员管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-04-04 09:04:35',
                'updated_at' => '2019-04-04 09:06:41',
            ),
            64 =>
            array (
                'id' => 123,
                'name' => '编辑会员',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 100,
                'route' => 'admin::user.edit',
                'url' => '',
                'group' => '会员管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-04-04 09:04:35',
                'updated_at' => '2019-04-04 09:06:41',
            ),
            65 =>
            array (
                'id' => 122,
                'name' => '保存会员',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 100,
                'route' => 'admin::user.save',
                'url' => '/admin/users',
                'group' => '会员管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-04-04 09:04:35',
                'updated_at' => '2019-04-04 09:06:41',
            ),
            66 =>
            array (
                'id' => 121,
                'name' => '新增会员',
                'pid' => 62,
                'status' => 1,
                'is_lock_name' => 0,
                'order' => 100,
                'route' => 'admin::user.create',
                'url' => '/admin/users/create',
                'group' => '会员管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-04-04 09:04:35',
                'updated_at' => '2019-04-04 09:06:41',
            ),
            67 =>
            array (
                'id' => 120,
                'name' => '会员列表数据接口',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 100,
                'route' => 'admin::user.list',
                'url' => '/admin/users/list',
                'group' => '会员管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-04-04 09:04:35',
                'updated_at' => '2019-04-08 14:07:28',
            ),
            68 =>
            array (
                'id' => 119,
                'name' => '会员列表',
                'pid' => 62,
                'status' => 1,
                'is_lock_name' => 0,
                'order' => 100,
                'route' => 'admin::user.index',
                'url' => '/admin/users',
                'group' => '会员管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-04-04 09:04:35',
                'updated_at' => '2019-04-04 09:06:41',
            ),
            69 =>
            array (
                'id' => 140,
                'name' => '删除标签',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 30,
                'route' => 'admin::tag.delete',
                'url' => '',
                'group' => '标签管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-10-23 09:49:15',
                'updated_at' => '2019-10-23 10:54:23',
            ),
            70 =>
            array (
                'id' => 139,
                'name' => '更新标签',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 30,
                'route' => 'admin::tag.update',
                'url' => '',
                'group' => '标签管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-10-23 09:49:15',
                'updated_at' => '2019-10-23 10:54:23',
            ),
            71 =>
            array (
                'id' => 138,
                'name' => '编辑标签',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 30,
                'route' => 'admin::tag.edit',
                'url' => '',
                'group' => '标签管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-10-23 09:49:15',
                'updated_at' => '2019-10-23 10:54:23',
            ),
            72 =>
            array (
                'id' => 137,
                'name' => '保存标签',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 30,
                'route' => 'admin::tag.save',
                'url' => '/admin/tags',
                'group' => '标签管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-10-23 09:49:15',
                'updated_at' => '2019-10-23 10:54:23',
            ),
            73 =>
            array (
                'id' => 136,
                'name' => '新增标签',
                'pid' => 62,
                'status' => 1,
                'is_lock_name' => 0,
                'order' => 30,
                'route' => 'admin::tag.create',
                'url' => '/admin/tags/create',
                'group' => '标签管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-10-23 09:49:15',
                'updated_at' => '2019-10-23 10:54:23',
            ),
            74 =>
            array (
                'id' => 135,
                'name' => '标签列表数据接口',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 30,
                'route' => 'admin::tag.list',
                'url' => '/admin/tags/list',
                'group' => '标签管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-10-23 09:49:15',
                'updated_at' => '2019-10-23 10:54:23',
            ),
            75 =>
            array (
                'id' => 134,
                'name' => '标签列表',
                'pid' => 62,
                'status' => 1,
                'is_lock_name' => 0,
                'order' => 29,
                'route' => 'admin::tag.index',
                'url' => '/admin/tags',
                'group' => '标签管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-10-23 09:49:15',
                'updated_at' => '2019-10-23 10:54:35',
            ),
            76 =>
            array (
                'id' => 133,
                'name' => '删除评论',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 90,
                'route' => 'admin::comment.delete',
                'url' => '',
                'group' => '评论管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-10-23 09:49:15',
                'updated_at' => '2019-10-23 11:03:11',
            ),
            77 =>
            array (
                'id' => 132,
                'name' => '更新评论',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 90,
                'route' => 'admin::comment.update',
                'url' => '',
                'group' => '评论管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-10-23 09:49:15',
                'updated_at' => '2019-10-23 11:03:11',
            ),
            78 =>
            array (
                'id' => 131,
                'name' => '编辑评论',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 90,
                'route' => 'admin::comment.edit',
                'url' => '',
                'group' => '评论管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-10-23 09:49:15',
                'updated_at' => '2019-10-23 11:03:11',
            ),
            79 =>
            array (
                'id' => 130,
                'name' => '评论列表数据接口',
                'pid' => 62,
                'status' => 0,
                'is_lock_name' => 0,
                'order' => 90,
                'route' => 'admin::comment.list',
                'url' => '/admin/comments/list',
                'group' => '评论管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-10-23 09:49:15',
                'updated_at' => '2019-10-23 11:03:11',
            ),
            80 =>
            array (
                'id' => 129,
                'name' => '评论列表',
                'pid' => 62,
                'status' => 1,
                'is_lock_name' => 0,
                'order' => 90,
                'route' => 'admin::comment.index',
                'url' => '/admin/comments',
                'group' => '评论管理',
                'guard_name' => 'admin',
                'remark' => '',
                'created_at' => '2019-10-23 09:49:15',
                'updated_at' => '2019-10-23 11:03:11',
            ),
            81 =>
            array (
                'id' => 149,
                'name' => '推荐列表',
                'pid' => 26,
                'status' => 1,
                'is_lock_name' => 0,
                'order' => 10,
                'route' => 'admin::recommends.index',
                'url' => '/admin/recommends',
                'group' => '推荐管理',
                'guard_name' => 'admin',
                'remark' => '1',
                'created_at' => '2021-04-21 09:43:59',
                'updated_at' => '2021-04-21 09:53:35',
            ),
            82 =>
            array (
                'id' => 146,
                'name' => '分类列表',
                'pid' => 26,
                'status' => 1,
                'is_lock_name' => 0,
                'order' => 1,
                'route' => 'admin::category',
                'url' => '/admin/categories/index',
                'group' => '分类管理',
                'guard_name' => 'admin',
                'remark' => '0',
                'created_at' => '2021-04-12 06:39:17',
                'updated_at' => '2021-04-12 07:44:59',
            ),
        ));


    }
}
